# Generated by Django 5.0.7 on 2024-08-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_story_storyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_stories', to='profiles.post'),
        ),
    ]
