# Generated by Django 5.0.7 on 2024-08-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_story_shared_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='content',
            new_name='description',
        ),
    ]
